import type { FormConfig } from "../types/form";

export const speakerSubmissionConfig: FormConfig = {
	meta: {
		id: "conference-speaker-submission",
		title: "Conference Speaker Submission",
		version: 1,
	},
	steps: [
		{ id: "speakerDetails", title: "Speaker Details" },
		{ id: "talkProposal", title: "Talk Proposal" },
		{ id: "sessionPreferences", title: "Session Preferences" },
		{ id: "availability", title: "Availability" },
		{ id: "logistics", title: "Travel Logistics" },
		{ id: "documents", title: "Documents" },
	],
	fields: [
		{
			name: "fullName",
			step: "speakerDetails",
			type: "text",
			label: "Full name",
			placeholder: "Jane Doe",
			validation: { required: true, minLength: 2 },
		},
		{
			name: "email",
			step: "speakerDetails",
			type: "text",
			label: "Email",
			placeholder: "jane@example.com",
			validation: {
				required: true,
				pattern: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
				message: "Enter a valid email",
			},
		},
		{
			name: "firstTimeSpeaker",
			step: "speakerDetails",
			type: "choiceCard",
			label: "Is this your first time speaking at a conference?",
			options: [
				{ value: "yes", label: "Yes", icon: "AcademicCapIcon" },
				{ value: "no", label: "No", icon: "MicrophoneIcon" },
			],
			answerHelp: {
				yes: "We'll pair you with a mentor to help prep your talk.",
				no: null,
			},
			validation: { required: true },
		},
		{
			name: "experienceLevel",
			step: "speakerDetails",
			type: "choiceChip",
			label: "Experience level",
			options: [
				{ value: "beginner", label: "Beginner" },
				{ value: "intermediate", label: "Intermediate" },
				{ value: "expert", label: "Expert" },
			],
			validation: { required: true },
		},

		{
			name: "talkFormat",
			step: "talkProposal",
			type: "visualCardSelect",
			label: "Talk format",
			options: [
				{ value: "workshop", label: "Workshop", icon: "AcademicCapIcon", description: "Hands-on, longer session" },
				{ value: "talk", label: "Talk", icon: "MicrophoneIcon", description: "Standard 40-minute session" },
				{ value: "panel", label: "Panel", icon: "UsersIcon", description: "Group discussion format" },
				{ value: "lightning", label: "Lightning Talk", icon: "BoltIcon", description: "Quick 5-10 minute talk" },
			],
			validation: { required: true },
		},
		{
			name: "talkTitle",
			step: "talkProposal",
			type: "text",
			label: "Talk title",
			placeholder: "e.g. Scaling Config-Driven UIs",
			validation: { required: true, minLength: 5 },
		},
		{
			name: "talkAbstract",
			step: "talkProposal",
			type: "textarea",
			label: "Talk abstract",
			placeholder: "What will attendees learn?",
			validation: { required: true, minLength: 50, message: "Give us at least a few sentences (50+ characters)" },
		},
		{
			name: "topics",
			step: "talkProposal",
			type: "chipMultiSelect",
			label: "Topics covered",
			options: [
				{ value: "ai", label: "AI", icon: "BoltIcon" },
				{ value: "web", label: "Web", icon: "GlobeAltIcon" },
				{ value: "devops", label: "DevOps", icon: "ArrowsRightLeftIcon" },
				{ value: "security", label: "Security", icon: "CheckIcon" },
				{ value: "design", label: "Design", icon: "PaintBrushIcon" },
			],
			validation: { required: true },
		},
		{
			name: "techStack",
			step: "talkProposal",
			type: "tagInput",
			label: "Tech stack you'll cover",
			optionsSource: "reference:techStack",
			allowCreate: true,
			multiple: true,
		},
		{
			name: "mentorAssignment",
			step: "talkProposal",
			type: "choiceCard",
			label: "Would you like a mentor assigned?",
			showIf: { field: "firstTimeSpeaker", equals: "yes" },
			options: [
				{ value: "yes", label: "Yes please", icon: "CheckIcon" },
				{ value: "no", label: "I'm okay without one", icon: "XMarkIcon" },
			],
			validation: { required: true },
		},

		{
			name: "sessionLength",
			step: "sessionPreferences",
			type: "select",
			label: "Preferred session length",
			options: [
				{ value: "20", label: "20 minutes" },
				{ value: "40", label: "40 minutes" },
				{ value: "60", label: "60 minutes" },
			],
			validation: { required: true },
		},
		{
			name: "needsAV",
			step: "sessionPreferences",
			type: "choiceChip",
			label: "Do you need extra A/V equipment?",
			options: [
				{ value: "yes", label: "Yes", icon: "CheckIcon" },
				{ value: "no", label: "No", icon: "XMarkIcon" },
			],
			validation: { required: true },
		},

		{
			name: "availabilityWindow",
			step: "availability",
			type: "dateRangePicker",
			label: "When are you available to present?",
			validation: { required: true },
		},
		{
			name: "travelRequired",
			step: "availability",
			type: "choiceCard",
			label: "Will you need to travel to the venue?",
			options: [
				{ value: "yes", label: "Yes", icon: "GlobeAltIcon" },
				{ value: "no", label: "No, I'm local / remote", icon: "HomeIcon" },
			],
			skipStepIf: { field: "travelRequired", equals: "no", goTo: "documents" },
			validation: { required: true },
		},

		{
			name: "country",
			step: "logistics",
			type: "select",
			label: "Country",
			optionsSource: "static:countries",
			validation: { required: true },
		},
		{
			name: "city",
			step: "logistics",
			type: "linkedSelect",
			label: "City",
			dependsOn: "country",
			optionsSource: "static:cityByCountry",
			validation: { required: true },
		},
		{
			name: "dietaryRestrictions",
			step: "logistics",
			type: "tagInput",
			label: "Dietary restrictions",
			placeholder: "Type and press Enter",
			multiple: true,
			optional: true,
		},

		{
			name: "slidesOrBio",
			step: "documents",
			type: "fileUpload",
			label: "Upload slides / speaker bio photo",
			multiple: true,
			deferable: true,
			optional: true,
			optionalLabel: "I'll send these closer to the event",
		},
		{
			name: "speakerNotes",
			step: "documents",
			type: "textarea",
			label: "Anything else the organizers should know?",
			optional: true,
		},
	],
};
