import type { FormConfig } from "../types/form";

export const warrantyClaimConfig: FormConfig = {
	meta: {
		id: "product-warranty-claim",
		title: "Product Warranty Claim",
		version: 1,
	},
	steps: [
		{ id: "productInfo", title: "Product Info" },
		{ id: "issueDetails", title: "Issue Details", layout: "grid" },
		{ id: "resolution", title: "Resolution" },
		{ id: "shipping", title: "Shipping" },
		{ id: "contact", title: "Contact" },
	],
	fields: [
		{
			name: "productName",
			step: "productInfo",
			type: "text",
			label: "Product name",
			placeholder: "e.g. Wireless Headphones Pro",
			validation: { required: true, minLength: 2 },
		},
		{
			name: "modelNumber",
			step: "productInfo",
			type: "text",
			label: "Model number",
			placeholder: "Found on the product label",
			optional: true,
		},
		{
			name: "purchaseLocation",
			step: "productInfo",
			type: "select",
			label: "Where did you buy it?",
			options: [
				{ value: "amazon", label: "Amazon" },
				{ value: "bestbuy", label: "Best Buy" },
				{ value: "walmart", label: "Walmart" },
				{ value: "official", label: "Official Store" },
				{ value: "other", label: "Other" },
			],
			validation: { required: true },
		},
		{
			name: "hasReceipt",
			step: "productInfo",
			type: "choiceCard",
			label: "Do you have the receipt or order confirmation?",
			options: [
				{ value: "yes", label: "Yes", icon: "CheckIcon" },
				{ value: "no", label: "No", icon: "XMarkIcon" },
			],
			answerHelp: {
				yes: "You'll be asked to upload it in the next steps.",
				no: "Claims without a receipt may take longer to process.",
			},
			validation: { required: true },
		},

		{
			name: "issueType",
			step: "issueDetails",
			type: "chipMultiSelect",
			label: "What's wrong with it?",
			options: [
				{ value: "broken", label: "Broken", icon: "XMarkIcon" },
				{ value: "not-working", label: "Not Working", icon: "BoltIcon" },
				{ value: "defective", label: "Defective", icon: "WrenchScrewdriverIcon" },
				{ value: "missing-parts", label: "Missing Parts", icon: "TicketIcon" },
			],
			validation: { required: true },
		},
		{
			name: "severity",
			step: "issueDetails",
			type: "choiceChip",
			label: "How severe is the issue?",
			options: [
				{ value: "minor", label: "Minor" },
				{ value: "moderate", label: "Moderate" },
				{ value: "severe", label: "Severe" },
			],
			validation: { required: true },
		},
		{
			name: "issueDescription",
			step: "issueDetails",
			type: "textarea",
			label: "Describe the issue",
			placeholder: "What happened, and when did it start?",
			validation: { required: true, minLength: 20 },
		},
		{
			name: "issuePhotos",
			step: "issueDetails",
			type: "fileUpload",
			label: "Upload photos of the issue",
			multiple: true,
			optional: true,
			optionalLabel: "Photos help us process your claim faster",
		},

		{
			name: "preferredResolution",
			step: "resolution",
			type: "visualCardSelect",
			label: "What resolution would you prefer?",
			options: [
				{ value: "repair", label: "Repair", icon: "WrenchScrewdriverIcon", description: "Send it in for repair" },
				{ value: "replace", label: "Replace", icon: "ArrowPathIcon", description: "Get a new unit" },
				{ value: "refund", label: "Refund", icon: "BanknotesIcon", description: "Money back to original payment" },
				{ value: "store-credit", label: "Store Credit", icon: "TicketIcon", description: "Credit for a future purchase" },
			],
			validation: { required: true },
		},
		{
			name: "needsReturnShipping",
			step: "resolution",
			type: "choiceCard",
			label: "Do you need a return shipping label?",
			options: [
				{ value: "yes", label: "Yes, I need to send the product back", icon: "GlobeAltIcon" },
				{ value: "no", label: "No, this doesn't require shipping", icon: "HomeIcon" },
			],
			skipStepIf: { field: "needsReturnShipping", equals: "no", goTo: "contact" },
			validation: { required: true },
		},

		{
			name: "country",
			step: "shipping",
			type: "select",
			label: "Country",
			optionsSource: "static:countries",
			validation: { required: true },
		},
		{
			name: "city",
			step: "shipping",
			type: "linkedSelect",
			label: "City",
			dependsOn: "country",
			optionsSource: "static:cityByCountry",
			validation: { required: true },
		},
		{
			name: "shippingAddress",
			step: "shipping",
			type: "addressAutocomplete",
			label: "Shipping address",
			placeholder: "Start typing your address",
			validation: { required: true },
		},
		{
			name: "preferredCarrier",
			step: "shipping",
			type: "tagInput",
			label: "Preferred carrier (optional)",
			optionsSource: "reference:carriers",
			optional: true,
		},

		{
			name: "contactName",
			step: "contact",
			type: "text",
			label: "Contact name",
			validation: { required: true, minLength: 2 },
		},
		{
			name: "contactPhone",
			step: "contact",
			type: "text",
			label: "Phone number",
			placeholder: "For updates on your claim",
			validation: { required: true, minLength: 7 },
		},
		{
			name: "additionalNotes",
			step: "contact",
			type: "textarea",
			label: "Anything else we should know?",
			optional: true,
		},
	],
};
